### ISSUE TITLE
NullReferenceException problem in WindowsBase.dll when I run PropertyGridDemo with Debug mode.

### ISSUE THREAD

**Issue by hasol81** [objorke/PropertyTools#39] opened 2015-01-14 12:59 UTC
I've just cloned the latest version of PropertyTools and tried to run PropertyGridDemo with "Debug" mode.
After clicking some examples on left tab, NullReferenceException was occured like this.

![image](https://cloud.githubusercontent.com/assets/6386799/5739113/6a2ecc3a-9c38-11e4-8e95-5232e7690870.png)

Sorry for Korean language and it might be...

An unhandled exception of type 'System.NullReferenceException' occurred in WindowsBase.dll
Additional information:  Object reference not set to an instance of an object.

I think that it might be a simple error, and I'm just expecting that this error will be fixed as soon.

**Comment by objorke** [comment] 2015-01-14 13:41
Do you remember which example?

**Comment by hasol81** [comment] 2015-01-14 13:49
"PropertyGridDemo" example.
I ran this example with Debug mode in NET40.
After running it, just click the left item, then you can see the same error.

**Comment by hasol81** [comment] 2015-03-12 05:41
I wonder that this issue has been fixed or not.
Kindly reminder.

I ran the recent source in my computer, but there's still an error like this issue.

I'm using VS2013 in Windows 8.1 (x64) now.

In case of my friend, he's using VS2013 in Windows 7 Pro (x64) now, and he does not have any errors like this issue.

I'm expecting this issue will be fixed soon.

**Comment by aldinei-sampaio** [comment] 2015-04-08 15:01
The problems seems to be VS IDE debugging related. Here is how I reproduce it:

1) Open the solution (the problem happens with both NET40 and NET45)
2) Set the project PropertyGridDemo_NET40 or PropertyGridDemo_NET45 as startup project
3) Click on Start
4) On the "PropertyGrid" menu, choose "Show declared only"

However, if I go to the bin\debug folder and run the PropertyGridDemo.exe, or if i choose "Start without debug" on VS, it runs fine without crashing.

I am using Windows 8.1 / VS 2013 Community Edition / All NuGet packages updated to most recent.

BTW, there is a compilation error on project UndoRedoDemo_NET40 / UndoRedoDemo_NET45 with the most recent version of Caliburn Micro. "Bootstrapper" class not found on AppBootstrapper.cs, line 20.

**Comment by aldinei-sampaio** [comment] 2015-04-08 15:53
If found the line of code that apparently is the cause of the problem.

In the project PropertyTools.Wpf_NET40 / PropertyTools.Wpf_NET45, the line 982 of the file PropertyGrid\PropertyGrid.cs is like this:

var tabItem = new TabItem { Header = tab, Padding = new Thickness(4), Name = tab.Id };

If I change this line like the following, the problem goes away:

var tabItem = new TabItem { Header = tab, Padding = new Thickness(4), Name = (tab.Id == null ? String.Empty : tab.Id) };

BTW, this bug seems the same as the #46.

**Comment by hasol81** [comment] 2015-04-08 16:51
Wow~!
Thank you so much, aldinei-sampaio.
I'm really excited to solve this issue~!!! :)

**Comment by objorke** [comment] 2015-04-08 21:29
@aldinei-sampaio please create an issue about updating the Caliburn Micro reference and fixing the compilation error in the UndoRedoDemo!

**Comment by aldinei-sampaio** [comment] 2015-04-09 00:50
Not sure what was the deal with Caliburn Micro, but I cant reproduce the issue anymore. All the solution is compiling just fine.

**Comment by objorke** [comment] 2015-04-10 11:49
Great, I am closing this issue. Re-open if you have more information.

**Closed by objorke** 2015-04-10 11:49 UTC
Labels: bug, help wanted, PropertyGrid
